### ISSUE TITLE
[環境構築]Android Build-tools 24 を入れてしまってビルドできない

### ISSUE THREAD

**Issue by amay077** [ytabuchi/XamarinHOL#2]
[Xamarinハンズオン浜松 #JXUG #jaghama - connpass](http://jaghama.connpass.com/event/33735/) では、5/30名 くらいの確率でハマってた（ビルドエラーになる）。Android Build-tools 24 を削除して解決。

「Android Build-tools 24 は入れないで」と注意書きしたほうがよさ気。

**Comment by ytabuchi** [comment]
手順書をアップデートしました。
