### ISSUE TITLE
[ハンズオン]プロジェクト作成直後、「とりあえずビルドして実行してみましょう」を入れる

### ISSUE THREAD

**Issue by amay077** [ytabuchi/XamarinHOL#3]
プロジェクト作成後、コーディングを進めてから初めてビルドする人がチラホラ。
そこでビルドエラーになると、環境構築に失敗しているのか、コーディングを失敗しているのか、本人も切り分けが難しくなるので、プロジェクト作成直後に、とりあえずビルド＆実行できることを確認してもらったほうが良さそう。

**Comment by amay077** [comment]
Xamarin Forms の方は、手順書に書いてあるとのこと（nuget からダウンロードの必要があるため）

**Comment by ytabuchi** [comment]
Android のドキュメントにビルドしましょう。を追加しました！
