### ISSUE TITLE
手順について

### ISSUE THREAD

**Issue by zephyrru** [ytabuchi/XamarinHOL#4]
ありがとうございます。資料参考になりました。

試しに手順に沿って自分の環境でやってみたのですが、"Android SDK Manager"でアップデートした後の手順で実機デバッグができなかったです。
対処としてはNugetでXamarin関係のパッケージをアップデートしたら動くようになりました。

Android SDK Manager・VS2015のアップデート状態他によって状況は変わるかもしれないですが、他の方で同様の状態になった人向けにissueを上げておきます。

**Comment by ytabuchi** [comment]
なるほど、Xamarin.Forms もアップデートしないと実機にデプロイできない？こちらでもやってみます。

**Comment by zephyrru** [comment]
最後は試行錯誤しながらでしたので、nugetでxamarin.formsアップデート後に再起動も行っています。
単純に新規プロジェクト作成前に再起動を一回かませば、そもそもnugetの方はいらなかった可能性もあります。
再現切り分けができていなくてすみません。
