### ISSUE TITLE
wikiの3_Xamarin.Formsの誤りについて

### ISSUE THREAD

**Issue by takapi-Jr** [ytabuchi/XamarinHOL#5]
2017/12/09のJXUG福岡のハンズオンにてXamarinHOLを使用しました。ありがとうございます。
コードスニペットに誤りと漏れがありました。
wikiのbranchを作成しコミットまでしましたが、pushができなかった(権限の問題？)ので、こちらでお知らせします。

3_Xamarin.Forms.md　226行目
誤：`using XF_Phoneword.Android;`
正：`using XF_Phoneword.Droid;`

3_Xamarin.Forms.md　531行目と532行目の間
正：下記メソッドの漏れ
```
        async void OnCallHistory(object sender, EventArgs e)
        {
            await Navigation.PushAsync(new CallHistoryPage());
        }
```

以上、よろしくお願いします。

**Comment by ytabuchi** [comment]
ご返信が遅くなりましてすみませんでした。
ご指摘の箇所、修正しました！！
